### ISSUE TITLE
Discord Chroma crashes when I wake my computer from sleep

### ISSUE THREAD

**Issue by infideleraser** [DELUUXE/DiscordChroma#16]
Anytime i wake my computer from sleep or hibernation, i get an error saying "Discord chroma has encountered an error, press to exit" or something along those lines. It only happens when I put my computer into sleep or hibernation.

**Comment by DELUUXE** [comment]
Could you attach the log file after this happened?
That is located in ``%appdata%\DiscordChroma`` -> log.txt

**Comment by infideleraser** [comment]
[log.txt](https://github.com/DELUUXE/DiscordChroma/files/6427734/log.txt)

**Comment by DELUUXE** [comment]
do you close discord before putting the computer in sleep mode?

**Comment by infideleraser** [comment]
i dont i just click sleep mode from the power menu

**Comment by DELUUXE** [comment]
hmm, I'll take a look

**Comment by DELUUXE** [comment]
I just released an update v0.4.10, if you start discordchroma it should auto update.
After its updated, could you check if the issue is still present?

**Comment by infideleraser** [comment]
issue isnt there anymore, however another issue arose and I'm not sure the cause, hopefully you know though
[log.txt](https://github.com/DELUUXE/DiscordChroma/files/6431787/log.txt)

**Comment by DELUUXE** [comment]
That is a connection issue to the Razer chroma ask server. Often restarting discord chroma fixes that or restarting the Razer ask service in windows services, if it happens successively (restarting your PC will also work).

I am going to try to get an automated solution for that soon.

**Comment by infideleraser** [comment]
ok perfect. i think a button that can restart the program would be great when it says "discord chroma has encountered an error", instead of just an exit button.
