### ISSUE TITLE
[Error] Crashes after about 20 seconds.

### ISSUE THREAD

**Issue by NightcoreRYT** [DELUUXE/DiscordChroma#4]
Hey, I would like to report an issue I am having with this app. I've tried using it today with no luck. I followed every step on the github page, and whenever I run the program, it crashes after about 20-30 seconds. 

I don't know if anyone else has had this issue but any help would be appreciated!

**Comment by NightcoreRYT** [comment]
https://cdn.discordapp.com/attachments/657559296539623468/658110416211148846/unknown.png

**Comment by DELUUXE** [comment]
Hey, sorry for the very late reply, i didnt not get notified of this issue.

Anyways, could you attach the log file, its located in: ``C:\Users\USERNAME\AppData\Roaming\DiscordChroma\log.txt``

thanks in advance

**Comment by DELUUXE** [comment]
I'll be closing this bug due to in activity.
feel free to re-open it if the problem persists.
