### ISSUE TITLE
No connection to local Chroma SDK Server

### ISSUE THREAD

**Issue by rl559** [DELUUXE/DiscordChroma#5]
Hello,

I understand that there is already an existing (closed) issue regarding this, but I am having a similar problem.

This is the screen that shows after a few seconds:
![image](https://user-images.githubusercontent.com/22898595/77584190-c799ba80-6eb8-11ea-99fa-84f8bf128c94.png)
This is the log report:
[log.txt](https://github.com/DELUUXE/DiscordChroma/files/4383476/log.txt)

Sorry again for making a duplicate!

**Comment by rl559** [comment]
I should probably go ahead and mention that restarting the application fixes nothing, the error still occurs. I did manage to authorize the app, but it was crashing even during that process as well.

**Comment by DELUUXE** [comment]
@rl559 it seems like the razer sdk server is not running correctly on your computer.
are other chroma apps working?
i suggest that you reinstall synapse, or atleast restart your computer.

**Comment by rl559** [comment]
Reinstalling synapse did the trick. Thank you!
